---
- name: Configure | php5-fpm | pool
  ini_file:
    dest: /etc/php5/fpm/pool.d/www.conf
    section: www
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'pm.max_children',      value: "{{ php_max_children }}"  }
    - { option: 'pm.start_servers',     value: "{{ php_start_servers }}" }
    - { option: 'pm.min_spare_servers', value: "{{ php_min_spare_servers }}" }
    - { option: 'pm.max_spare_servers', value: "{{ php_max_spare_servers }}" }
    - { option: 'pm.max_requests',      value: "{{ php_max_requests }}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - ini-configuration
    - performance-tuning
    - php

- name: Configure | php5-fpm | php.ini
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'expose_php',      value: "{% if php_hide_version %}Off{% else %}On{% endif %}" }
    - { option: 'short_open_tag',  value: "{% if php_short_open_tag %}On{% else %}Off{% endif %}" }
    - { option: 'display_errors',  value: "{% if php_display_errors %}On{% else %}Off{% endif %}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - improves-security
    - php

- name: Configure | php5-fpm | php-fpm.conf
  ini_file:
    dest: /etc/php5/fpm/php-fpm.conf
    section: general
    option: listen
    value: "{{ php_fpm_socket_path }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - ini-configuration
    - improves-security
    - unix-socket
    - php
