---
- name: Configure | php5-fpm | php-fpm.conf
  ini_file:
    dest: /etc/php5/fpm/php-fpm.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'listen',                  value: "{{ php_fpm_socket_path }}" }
    - { option: 'error_log',               value: "{{ php_fpm_log_path }}" }
    - { option: 'pid',                     value: "{{ php_fpm_pidfile_path }}" }
    - { option: 'request_slowlog_timeout', value: "{{ php_slow_threshold }}" }
    - { option: 'slowlog',                 value: "{{ php_slow_log_path }}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - php

- name: Configure | php5-fpm | pool
  ini_file:
    dest: /etc/php5/fpm/pool.d/www.conf
    section: www
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'listen',                     value: "{{ php_fpm_socket_path }}" }
    - { option: 'pm.max_children',            value: "{{ php_max_children }}"  }
    - { option: 'pm.max_requests',            value: "{{ php_max_requests }}" }
    - { option: 'pm.max_spare_servers',       value: "{{ php_max_spare_servers }}" }
    - { option: 'pm.min_spare_servers',       value: "{{ php_min_spare_servers }}" }
    - { option: 'pm.start_servers',           value: "{{ php_start_servers }}" }
    - { option: 'request_terminate_timeout',  value: "{{ php_request_terminate_timeout }}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - php

- name: Configure | php5-fpm | php.ini
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'cgi.fix_pathinfo',    value: "{% if php_cgi_fix_pathinfo %}1{% else %}0{% endif %}" }
    - { option: 'display_errors',      value: "{% if php_display_errors %}On{% else %}Off{% endif %}" }
    - { option: 'error_log',           value: "{{ php_error_log_path }}" }
    - { option: 'expose_php',          value: "{% if php_hide_version %}Off{% else %}On{% endif %}" }
    - { option: 'post_max_size',       value: "{{ php_post_max_size }}" }
    - { option: 'short_open_tag',      value: "{% if php_short_open_tag %}On{% else %}Off{% endif %}" }
    - { option: 'upload_max_filesize', value: "{{ php_upload_max_filesize }}" }
    - { option: 'memory_limit',        value: "{{ php_memory_limit }}"}
    - { option: 'max_execution_time',  value: "{{ php_max_execution_time }}"}
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - php
