---
- name: "Directory Exists | {{ php_runtime_root }}"
  file:
    state: directory
    path: "{{ php_runtime_root }}"
    owner: "{{ php_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - php

- name: Upload Config | monit | php5-fpm
  template:
    src: etc/monit/conf.d/php5-fpm
    dest: /etc/monit/conf.d/php5-fpm
  notify: Reload Service | monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Configure | php5-fpm | pidfile
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php-fpm.conf
    regexp: '^;* *pid '
    line: 'pid = {{ php_fpm_pidfile_path }}'
  notify: Reload Service | php5-fpm

- name: Confirm Monitoring | php5-fpm
  monit:
    state: present
    name: php5-fpm
