---
- name: Directories Exists
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0775
  with_items:
    - "{{ php_log_root }}"
    - "{{ php_runtime_root }}"
  tags:
    - filesystem-layout
    - php

- name: Files Exist with Correct Permissions
  file:
    state: touch
    path: "{{ item }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0664
  with_items:
    - "{{ php_fpm_log_path }}"
    - "{{ php_error_log_path }}"
    - "{{ php_slow_log_path }}"
