---
- name: "Directory Exists | {{ php_log_root }}"
  file:
    state: directory
    path: "{{ php_log_root }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0775
  tags:
    - filesystem-layout
    - php

- name: "Directory Exists | {{ php_runtime_root }}"
  file:
    state: directory
    path: "{{ php_runtime_root }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0775
  tags:
    - filesystem-layout
    - php


- name: Files Exist
  copy:
    content: ""
    dest: "{{ item }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0664
    force: no
  with_items:
    - "{{ php_fpm_log_path }}"
    - "{{ php_error_log_path }}"
    - "{{ php_slow_log_path }}"

- name: Files Have Correct Permissions
  file:
    state: file
    path: "{{ item }}"
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0664
  with_items:
    - "{{ php_fpm_log_path }}"
    - "{{ php_error_log_path }}"
    - "{{ php_slow_log_path }}"
